# Generated by Django 4.0.4 on 2022-05-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=200, null=True)),
                ('date_of_booking', models.DateTimeField()),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=200, null=True)),
                ('bus_plate_number', models.CharField(max_length=200, null=True)),
                ('bus_type', models.CharField(max_length=200, null=True)),
                ('bus_capacity', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone1', models.CharField(max_length=200, null=True)),
                ('phone2', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_description', models.CharField(max_length=200, null=True)),
                ('parcel_starting_point', models.CharField(max_length=200, null=True)),
                ('parcel_destination', models.CharField(max_length=200, null=True)),
                ('parcel_departure_datetime', models.DateTimeField()),
                ('parcel_estimated_arrival_time', models.DateTimeField()),
                ('parcel_fare_amount', models.CharField(max_length=200, null=True)),
                ('parcel_status', models.CharField(choices=[('Station Recieved', 'Station Recieved'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('parcel_remarks', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('departure_datetime', models.DateTimeField()),
                ('estimated_arrival_time', models.CharField(max_length=200, null=True)),
                ('travel_fare_amount', models.IntegerField()),
                ('remarks', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
