# Generated by Django 4.0.4 on 2022-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_accountcategory_user_delete_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
