# Generated by Django 4.0.4 on 2022-05-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_bus_bus_type_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelschedule',
            name='avaible_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='travelschedule',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
