# Generated by Django 4.0.4 on 2022-05-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_travelschedule_avaible_seats_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelSchedule',
            new_name='Trip',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
